config/routes.rb
Rails.application.routes.draw do
  resources :clients
  devise_for :users
  get 'welcome/index'
  get 'welcome/store'
  get 'welcome/garage'
  get 'welcome/service'

  root 'welcome#index'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  # ----------------------------------------------------------------------
  # == Associations == #
  # ----------------------------------------------------------------------

  belongs_to :user
  has_many :services, dependent: :destroy

end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
  append :remote_ip, :user_agent
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :contact_number
  attribute :message
  validates :message,   length: { in: 5..2000 }
  attribute :nickname,  :captcha  => true


  def headers
    {
      subject: 'Contacto motortowncr.com',
      to: 'motor_uruca@watersonn.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/service.rb
class Service < ApplicationRecord
  
  # ----------------------------------------------------------------------
  # == Associations == #
  # ----------------------------------------------------------------------

  belongs_to :car

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # ----------------------------------------------------------------------
  # == Associations == #
  # ----------------------------------------------------------------------

  has_many :cars,      dependent: :destroy
  has_many :services,  through: :cars

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :contact_number)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if verify_recaptcha
      if @contact.deliver
        flash.now[:error] = nil
        flash.now[:notice] = 'Gracias por su mensaje. Lo estaremos contactando pronto.'
      else
        flash.now[:error] = 'No se pudo enviar su mensaje.'
        render welcome: "welcome/index"
      end
      
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :contact_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Contact number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= client.contact_number %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @client.contact_number %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/contacts/_new.html.erb
<%= simple_form_for @contact do |f| %>
  <%= f.input :name, required: true, label: "Nombre y Apellido(s):" %>
  <%= f.input :email, required: true, label: "Correo Electr&oacute;nico:".html_safe %>
  <%= f.input :contact_number, required: true, label: "N&uacute;mero de Telefono:".html_safe %>
  <%= f.input :message, required: true, label: "Mensaje:" %>
  <div class= "hidden">
    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
  </div>

  <small class="form-text text-muted">Aseg&uacute;rese de llenar la sigiente casilla</small>

  <%= recaptcha_tags hl: 'es'%>
  
  <br/>

  <%= f.button :submit, 'Enviar mensaje', :class=> "btn btn-dark" %>
<% end %>

app/views/contacts/create.html.erb
<div class="container extra-space-top">
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>

	<br><br>

	<%= link_to "Volver a pagina principal",
    welcome_index_path,
    class: "btn btn-secondary",
    role: "button"
  %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motor Town | Un mundo de accesorios...</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar navbar-expand-md fixed-top navbar-dark custom-navbar">
    <%= link_to image_tag("MotorTown-Color.png"), root_path, class: "nav-item motor-town-logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#about">Acerca</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#location">&iquest;D&oacute;nde estamos?</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contact">Cont&aacute;ctenos</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">M&aacute;s...</a>
          <div class="dropdown-menu custom-navbar" aria-labelledby="dropdown01">
            <%= link_to "Tienda", welcome_store_path, class: "dropdown-item" %>
            <%= link_to "Taller", welcome_garage_path, class: "dropdown-item" %>
            <%= link_to "Servicio", welcome_service_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>

      <div>
        <% if user_signed_in? %>
          <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to 'Ingresar', new_user_session_path, class: "nav-link disabled" %>
        <% end %>
      </div>

    </div>
    
  </nav>

  <body>
    <%= yield %>
  </body>

  <footer class="container-fluid text-center custom-footer">

    <div class="row justify-content-center">
      <div class="col-sm-1 welcome-icon">
        <%= link_to "https://www.facebook.com/motortowncr",  target: "_blank" do %>
          <%= image_tag "facebook-icon.png", class: "social-media-icon", alt: "Facebook icon"%>
        <% end %>
      </div>
      <div class="col-sm-1 welcome-icon">
        <%= link_to "https://www.instagram.com/motortowncr/", class: "social-media-icon", target: "_blank" do %>
          <%= image_tag "instagram-icon.png", class: "social-media-icon", alt: "Instagram icon"%>
        <% end %>      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <p>&copy; Motor Town 2017 - 2018 <br>
        <small>Creado por: <a target="_blank" href="http://germanosta.com/">gemanosta.com</a></small></p>
      </div>
    </div>
  </footer>

</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/garage.html.erb
<main>

  <div class="containe-fluid static-page garage-page">

    <div class="row justify-content-center">
      <h1 class="display-3">Taller</h1>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-8">
        <p>
          Nuestro taller esta capacitado con el m&aacute;s alto personal, herramientas
          y maquinaria para poder bridnarle los mejores servicios.
          <br><br>
          Nos destacamos por un r&eacute;pido servicio de calidad.
          Trabajamos con las mejores marcas para que su carro pueda afrontar
          caulquier aventura y trabajo.
          <br><br>
          Dentro de nuestros servicios usted podr&aacute; encontrar:
        </p>
      </div>
    </div>

      <div class="row justify-content-center">
      <div class="col-md-4">
        <ul>
          <li>Mec&aacute;nica r&aacute;pida</li>
          <li>Cambios de aceite</li>
          <li>Filtros de aire</li>
          <li>Reparaci&oacute;n de llantas</li>
          <li>Bater&iacute;as</li>

        </ul>
      </div>

      <div class="col-md-4">
        <ul>
          <li>Frenos</li>
          <li>Lavados</li>
          <li>Puidos</li>
          <li>Instalaciones el&eacute;ctricas</li>
          <li>Modificaciones 4x4</li>
        </ul>
      </div>
    </div>

  </div>

</main>

app/views/welcome/index.html.erb
<main role="main">

 <!-- ***************** WELCOME SECTION *****************  -->

  <div class="container-fluid text-center welcome-intro">
    <div class="row welcome-slogan">
      <div class="col-sm align-self-center">
        <h1 class="display-3 font-weight-bold">Un mundo de accesorios</h1>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-sm-1 welcome-icon">
        <%= link_to "https://www.facebook.com/motortowncr",  target: "_blank" do %>
          <%= image_tag "facebook-icon.png", class: "social-media-icon", alt: "Facebook icon"%>
        <% end %>
      </div>
      <div class="col-sm-1 welcome-icon">
        <%= link_to "https://www.instagram.com/motortowncr/", class: "social-media-icon", target: "_blank" do %>
          <%= image_tag "instagram-icon.png", class: "social-media-icon", alt: "Instagram icon"%>
        <% end %>      </div>
    </div>
  </div>

   <!-- ***************** END WELCOME SECTION *****************  -->

  <!-- ***************** ABOUT SECTION *****************  -->
  
  <div class="container-fluid text-center about-container" id="about">
    <div class="row">
      <div class="col align-self-center about-title">
        <h2>&iquest;Por qu&eacute; somos los mejores?</h2>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-2 ml-2 mr-2">
        <%= image_tag "variety-icon.png", class: "about-icon", alt: "Variety icon"%>
        <h4>VARIEDAD</h4>
        <p>Tenemos todo tipo de accesorios y servicios para cualquier aventura o trabajo</p>
        <p>
          <%= link_to "Ver detalles &raquo;".html_safe,
          welcome_store_path,
          class: "btn btn-dark",
          role: "button"
          %>
        </p>
      </div>
      <div class="col-md-2 ml-2 mr-2">
        <%= image_tag "service-icon.png", class: "about-icon", alt: "Service icon"%>
        <h4>SERVICIOS</h4>
        <p>Ofrecemos una amplia variedad de servicios, ya sean b&aacute;sicos o modificaciones</p>
        <p>
          <%= link_to "Ver detalles &raquo;".html_safe,
          welcome_garage_path,
          class: "btn btn-dark",
          role: "button"
          %>
        </p>
      </div>
      <div class="col-md-2 ml-2 mr-2">
        <%= image_tag "quality-icon.png", class: "about-icon", alt: "Quality icon"%>
        <h4>CALIDAD</h4>
        <p>Nos preocupamos por tener las mejores marcas en accesorios y servicios a los mejores precios</p>
        <p>
          <%= link_to "Ver detalles &raquo;".html_safe,
          welcome_service_path,
          class: "btn btn-dark",
          role: "button"
          %>
        </p>
      </div>

    </div>

    
  </div>


  <!-- ***************** END ABOUT SECTION *****************  -->

  <!-- ***************** LOCATION SECTION *****************  -->


    <div class="container" id="location">
      <h1 class="display-4">Horario</h1>
      <div class="row">
        <div class="col-md-6">
          <ul>
            <li><b>Lunes a Viernes:</b> 8:00am - 6:00pm</li>
            <li><b>S&aacute;bado:</b> 8:00am - 3:00pm</li>
          </ul>
        </div>
        <div class="col-md-6">
          <ul>
            <li><b>Tel&eacute;fono:</b> 2232-2313</li>
            <li><b>Direcci&oacute;n:</b> 150mts sur de La Pozuelo, La Uruca</li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          
          <%= link_to "https://www.google.co.cr/maps/place/Motor+Town/@9.9510106,-84.1138038,17z/data=!3m1!4b1!4m5!3m4!1s0x8fa0fb4ffec9272d:0x50a953eb0b44805c!8m2!3d9.9510053!4d-84.1116151?hl=en", target: "_blank" do %>
            <%= image_tag "location.png", class: "img-fluid", alt: "Direccion de Motor Town"%>
          <% end %>

        </div>
      </div>
    </div>

    <!-- ***************** END LOCATION SECTION *****************  -->
    
    <!-- ***************** CONTACT SECTION *****************  -->

    <hr>
    <div class="container" id="contact">
      <h1 class="display-4">Cont&aacute;ctenos</h1>
      <%= render "contacts/new" %>
    </div>

    <!-- ***************** END CONTACT SECTION *****************  -->

  </main>

app/views/welcome/service.html.erb
<main>

  <div class="container-fluid static-page service-page">

    <div class="row justify-content-center">
      <h1 class="display-3">Nuestra Misi&oacute;n</h1>
    </div>

    <div class="row justify-content-center info-description">

      <div class="col-md-8">
        <p>
          En nuestro taller el cliente siempre va primero. En Motor Town se
          imparten los valores de honradez, amablidad, responsabilidad y puntualidad.
          <br><br>
          Nos preocupamos por usar los mejores materiales en nuestros trabajos y productos. <br>
          Adem&aacute;s estamos comprometidos en ayudar al medio ambiente.         
        </p>
      </div>

    </div>

  </div>

</main>

app/views/welcome/store.html.erb
<main>

  <div class="containe-fluid static-page store-page">

    <div class="row justify-content-center">
      <h1 class="display-3">Tienda</h1>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-8">
        <p>
          En Motor Town podr&aacute; encontrar todo tipo de productos para su veh&iacute;culo.
          Nuestro objetivo es brindarle el mejor servicio y atenci&oacute;n a los mejores precios.
          Llevamos sirviendole al pa&iacute;s por m&aacute;s de 15 anos.
          <br><br>
          Trabajamos con marcas de excelente calidad y con alto reconomiento nacional
          e internacional como German-Tek, Strona, Sirius, The Treatment, Pennzoil y Akron.
          <br><br>
          Dentro de nuestros productos usted podra encontrar:
        </p>
      </div>
    </div>


    <div class="row justify-content-center">
      <div class="col-md-4">
        <ul>
          <li>Mataburros</li>
          <li>Estribos</li>
          <li>Racks</li>
          <li>Canastas</li>
          <li>Lonas</li>
          <li>Cajas de Herramientas</li>
        </ul>
      </div>

      <div class="col-md-4">
        <ul>
          <li>Halogenos</li>
          <li>LEDs</li>
          <li>Herramientas</li>
          <li>Productos de limpieza</li>
          <li>Kit de emergencia</li>
          <li>Y m&aacute;s...</li>
        </ul>
      </div>
    </div>

  </div>

</main>